version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  reviewers:
  - ivan-kolmychek-devv
  - tetiana-kolmychek-devv
  assignees:
  - ivan-kolmychek-devv
  - tetiana-kolmychek-devv
  versioning-strategy: increase
  ignore:
  - dependency-name: css-loader
    versions:
    - ">= 2.0.0.a, < 2.0.1"
  - dependency-name: css-loader
    versions:
    - ">= 2.0.1.a, < 2.0.2"
  - dependency-name: css-loader
    versions:
    - ">= 2.0.2.a, < 2.0.3"
  - dependency-name: css-loader
    versions:
    - ">= 2.1.0.a, < 2.1.1"
  - dependency-name: css-loader
    versions:
    - ">= 2.1.1.a, < 2.1.2"
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
  - dependency-name: ua-parser-js
    versions:
    - 0.7.23
    - 0.7.24
    - 0.7.25
    - 0.7.26
    - 0.7.27
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
